export const SET_MOVIES_LIST = 'SET_MOVIES_LIST';
export const SET_SEARCH_INPUT_VALUE = 'SET_SEARCH_INPUT_VALUE';
export const SET_ACTIVE_MOVIE_ID = 'SET_ACTIVE_MOVIE_ID';
export const SET_MOVIES_ORDER = 'SET_MOVIES_ORDER';
