export const SET_MOVIES_LIST = 'SET_MOVIES_LIST';
export const SET_SEARCH_INPUT_VALUE = 'SET_SEARCH_INPUT_VALUE';
export const SET_ACTIVE_MOVIE_ID = 'SET_ACTIVE_MOVIE_ID';
export const SET_MOVIES_ORDER = 'SET_MOVIES_ORDER';
export const ADD_LIKE_TO_MOVIE_ITEM = 'ADD_LIKE_TO_MOVIE_ITEM';
export const REMOVE_LIKE_FROM_MOVIE_ITEM = 'REMOVE_LIKE_FROM_MOVIE_ITEM';
export const SET_RATING_TO_MOVIE_ITEM = 'SET_RATING_TO_MOVIE_ITEM';
